import type { WorkspaceData } from './types'

/**
 * Seed data so the workspace is useful on first load. The owner can wipe and
 * replace this via the dataset import/reset controls.
 */
export const SEED: WorkspaceData = {
  team: [
    { id: 'isr-1', name: 'Neha Sharma', role: 'ISR', email: 'neha@company.com' },
    { id: 'isr-2', name: 'Arjun Mehta', role: 'ISR', email: 'arjun@company.com' },
    { id: 'isr-3', name: 'Priya Nair', role: 'ISR', email: 'priya@company.com' },
    { id: 'sales-1', name: 'Rahul Verma', role: 'Sales', email: 'rahul@company.com' },
    { id: 'sales-2', name: 'Sana Kapoor', role: 'Sales', email: 'sana@company.com' },
  ],
  customers: [
    {
      id: 'c-1',
      name: 'Rohit Vishwakarma',
      title: 'Associate Head - IT',
      company: 'Perfetti Van Melle',
      email: 'rohit.vishwakarma@perfetti.com',
      phone: '+91 97110 03473',
      city: 'Mumbai',
      source: 'Signature paste',
      status: 'Assigned',
      focus: true,
      assignedIsrId: 'isr-1',
      createdAt: '2026-08-20T09:00:00.000Z',
    },
    {
      id: 'c-2',
      name: 'Anita Desai',
      title: 'CISO',
      company: 'KEC International Ltd',
      email: 'anita.desai@kecrpg.com',
      phone: '+91 98200 11223',
      city: 'Mumbai',
      source: 'Inbound',
      status: 'Working',
      focus: true,
      assignedIsrId: 'isr-2',
      createdAt: '2026-08-22T09:00:00.000Z',
    },
    {
      id: 'c-3',
      name: 'Vikram Rao',
      title: 'Head of Infrastructure',
      company: 'RPG Enterprises Ltd',
      email: 'vikram.rao@rpg.in',
      phone: '+91 99000 44556',
      city: 'Pune',
      source: 'Event',
      status: 'Contacted',
      focus: false,
      assignedIsrId: 'isr-1',
      createdAt: '2026-08-25T09:00:00.000Z',
    },
    {
      id: 'c-4',
      name: 'Sunil Gupta',
      title: 'IT Manager',
      company: 'Aarti Industries',
      email: 'sunil.gupta@aarti.com',
      phone: '+91 98765 43210',
      city: 'Vadodara',
      source: 'Import: Delhi.xlsx',
      status: 'New',
      focus: false,
      createdAt: '2026-08-28T09:00:00.000Z',
    },
    {
      id: 'c-5',
      name: 'Meera Iyer',
      title: 'VP Technology',
      company: '3I Infotech Ltd',
      email: 'meera.iyer@3i-infotech.com',
      phone: '+91 90000 12345',
      city: 'Bangalore',
      source: 'Referral',
      status: 'Qualified',
      focus: true,
      assignedIsrId: 'isr-3',
      createdAt: '2026-08-30T09:00:00.000Z',
    },
  ],
  deals: [
    {
      id: 'd-1',
      title: 'KEC — Email security rollout',
      company: 'KEC International Ltd',
      customerId: 'c-2',
      value: 500000,
      stage: 'Proposal',
      probability: 60,
      isrId: 'isr-2',
      salesId: 'sales-1',
      startDate: '2026-08-05',
      closeDate: '2026-10-15',
      createdAt: '2026-08-05T09:00:00.000Z',
    },
    {
      id: 'd-2',
      title: 'RPG — Awareness training pilot',
      company: 'RPG Enterprises Ltd',
      customerId: 'c-3',
      value: 85000,
      stage: 'Qualification',
      probability: 30,
      isrId: 'isr-1',
      salesId: 'sales-2',
      startDate: '2026-08-20',
      closeDate: '2026-11-10',
      createdAt: '2026-08-20T09:00:00.000Z',
    },
    {
      id: 'd-3',
      title: 'Aarti — Phishing simulation',
      company: 'Aarti Industries',
      customerId: 'c-4',
      value: 368000,
      stage: 'Demo',
      probability: 45,
      isrId: 'isr-1',
      salesId: 'sales-1',
      startDate: '2026-09-01',
      closeDate: '2026-12-05',
      createdAt: '2026-09-01T09:00:00.000Z',
    },
    {
      id: 'd-4',
      title: '3I Infotech — Platform expansion',
      company: '3I Infotech Ltd',
      customerId: 'c-5',
      value: 240000,
      stage: 'Negotiation',
      probability: 75,
      isrId: 'isr-3',
      salesId: 'sales-2',
      startDate: '2026-07-15',
      closeDate: '2026-09-25',
      createdAt: '2026-07-15T09:00:00.000Z',
    },
    {
      id: 'd-5',
      title: 'Perfetti — Renewal + upsell',
      company: 'Perfetti Van Melle',
      customerId: 'c-1',
      value: 150000,
      stage: 'Won',
      probability: 100,
      isrId: 'isr-1',
      salesId: 'sales-1',
      startDate: '2026-06-10',
      closeDate: '2026-08-28',
      createdAt: '2026-06-10T09:00:00.000Z',
    },
  ],
}
